# We have a function set of for() loops that create the input file
# for the discrete choice analysis.

# we also have a functioning discrete choice code from Cam
# that's been annotated extensively with our notes. Also we have
# Cam's old dataset

# the next step is to extract some habitat data (LiDAR, perhaps??)
# at all 39,500 locations generated by Nicole/random points

# Finally, the last step is running the discrete choice analysis with 
# these data

# in the meantime, Nicole: spend some time reading a few papers about
# discrete choice and bayesian models/how they work (there's probably
# some youtube videos n shit on this too)